@startuml
actor "Joeueur" as Player
participant "Interface de Jeu" as UI
participant "Système de gestion de jeu" as GameSystem

Player -> UI: 1: choisirModeDeJeu()
UI -> GameSystem: 1-1: listerModesDisponibles()
GameSystem --> UI: 1-1-1: Liste des modes disponibles
UI --> Player: 1-1-1-1: Modes de jeu

alt [Jouer contre IA debutante]
    Player -> UI: 2: choisirIADebutant()
    UI -> GameSystem: 2-1: enregistrerLaSelection()
else [contre IA avancee]
    Player -> UI: 3: choisirIAAvance()
    UI -> GameSystem: 3-1: enregistrerLaSelection()
end

alt [Jouer contre Humain]
    Player -> UI: 4: choisirHumain()
    UI -> GameSystem: 4-1: enregistrerLaSelection()
end

GameSystem --> UI: 5: confirmation de sélection
UI --> Player: 5-1:  Mode choisi

@enduml